"""Update Book Unique Constraint

Revision ID: 73f843709e10
Revises: f2e5b92fda76
Create Date: 2024-10-04 22:07:14.161431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73f843709e10'
down_revision: Union[str, None] = 'f2e5b92fda76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_title_author', 'books', type_='unique')
    op.create_unique_constraint('unique_title_author', 'books', ['Title', 'Author', 'user_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_title_author', 'books', type_='unique')
    op.create_unique_constraint('unique_title_author', 'books', ['Title', 'Author'])
    # ### end Alembic commands ###
