"""Add Reviews Table

Revision ID: dacdb68b5fc5
Revises: 73f843709e10
Create Date: 2024-10-07 22:12:00.813884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dacdb68b5fc5'
down_revision: Union[str, None] = '73f843709e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('review_text', sa.VARCHAR(length=250), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('book_uid', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_constraint('books_user_uid_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_user_uid_fkey', 'books', 'users', ['user_uid'], ['uid'], ondelete='SET NULL')
    op.drop_table('reviews')
    # ### end Alembic commands ###
